#!/bin/bash

# TODO check that running as root

kube-vip () {
  podman run --network host --rm "ghcr.io/kube-vip/kube-vip:$KVVERSION" "$@"
}

export VIP=192.168.42.69
export INTERFACE=enp0s31f6
export KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")

kube-vip manifest pod \
   --interface "$INTERFACE" \
   --address "$VIP" \
   --controlplane \
   --services \
   --arp \
   --leaderElection | tee /etc/kubernetes/manifests/kube-vip.yaml


