#!/bin/bash

kubeadm init \
  --control-plane-endpoint k8s:6443 \
  --pod-network-cidr 172.16.0.0/12 \
  --service-cidr 10.96.0.0/12 \
  --kubernetes-version 1.24.6 \
  --skip-certificate-key-print \
  --upload-certs
