- name: config network bridge
  hosts: k8snodes
  become: yes
  tasks:

    - name: enable br_netfilter module
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - ansible.builtin.shell: modprobe overlay
    - ansible.builtin.shell: modprobe br_netfilter

    - name: enable iptables for bridged traffic
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1

    - name: reload sysctl
      ansible.builtin.shell: sysctl --system
