network:
  ethernets:
    ens33:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.0.1/16
        - 192.168.10.254/24
      routes:
        - to: default
          via: 192.168.1.1
        - to: 192.168.10.0/24
          via: 192.168.10.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
  version: 2
