- name: Add CoreDNS group
  group:
    name: "{{ coredns_group }}"

- name: Add CoreDNS user
  user:
    name: "{{ coredns_user }}"
    group: "{{ coredns_group }}"
    shell: /bin/bash
    create_home: no

- name: Create CoreDNS config directory
  file:
    path: "{{ coredns_config_path }}"
    state: directory
    mode: 0755
    owner: "{{ coredns_user }}"
    group: "{{ coredns_group }}"