#!/usr/bin/env bash

## This assumes you have the following in your .bashrc:
##  export ANSIBLE_INVENTORY="$HOME/.config/ansible/inventory.yaml"

if ! command -v ansible; then
  echo "Ansible isn't installed. Skipping."
  exit 1
fi

mkdir -p $HOME/.config/ansible
ln -sf "$PWD/inventory.yaml" "$HOME/.config/ansible/inventory.yaml"
ln -sf "$PWD/config.ini" "$HOME/.config/ansible/config.ini"
